---
# tasks file for mariadb

#- name: Create config.inc.php
#  template: src="phpmyadmin.config.php.j2" dest="/usr/share/phpmyadmin/config.inc.php"
#
#- name: Create /var/lib/mysql directory
#  file: path="/var/lib/mysql" recurse=yes state=directory mode="u=rwx,g=rwx,o=rx"
#  args:
#    group: "{{ mariadb_group }}"
#    owner: "{{ mariadb_user }}"
#
#- name: Restart nginx
#  service: name=nginx state=restarted
#
#- name: Restart mariadb
#  service: name=mariadb state=restarted
#
#- meta: end_play
#  when: mariadb_end_play == true
#

# Jessie
- include: main-debian8.yml
  when: ansible_distribution == 'Debian'
        and ansible_distribution_major_version == '8'

# Settings
- name: Create /etc/mysql/my.cnf
  template: src="my.cnf.j2" dest="/etc/mysql/my.cnf" owner=root group=root mode=0644
  notify: restart-mysql

# Root user
- name: Update MariaDB root user password
  mysql_user: check_implicit_admin=no name=root host="{{ item }}" password="{{ mariadb_root_password }}"
  when: (not (mariadb_root_password is undefined or mariadb_root_password|trim == "")) and (mariadb_disable_user_management == false)
  ignore_errors: yes
  with_items:
    - "::1"
    - "{{ inventory_hostname }}"
    - "{{ inventory_hostname_short }}"
    - "localhost"
    - "127.0.0.1"

- name: Copy .my.cnf file to root home
  template: src=root.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600 force=yes
  when: not (mariadb_root_password is undefined or mariadb_root_password|trim == "")

- name: Update MariaDB root user password when root/nopassword allowed
  mysql_user: check_implicit_admin=yes name=root password="{{ mariadb_root_password }}"
  when: mariadb_disable_user_management == false

# Remove local
- name: Set root password
  mysql_user: login_user=root login_password="{{ mariadb_root_password }}" host={{ item }} name='' state=absent
  with_items:
    - "::1"
    - "{{ inventory_hostname }}"
    - "{{ inventory_hostname_short }}"
    - "localhost"
    - "127.0.0.1"
  when: mariadb_disable_user_management == false

# PHPMyAdmin
- include: phpmyadmin.yml
  when: mariadb_phpmyadmin_install == true

# Percona tools
- include: percona.yml
  when: mariadb_percona_install == true

# Start
- name: Start the mariadb service
  service: name=mariadb state=started enabled=yes
