---
# tasks file for mariadb

# Jessie
- include: main-debian8.yml
  when: ansible_distribution == 'Debian'
        and ansible_distribution_major_version == '8'

# Settings
- template: src="my.cnf.j2" dest="/etc/mysql/my.cnf" owner=root group=root mode=0644
  notify: restart-mysql

# Root user
- name: Update MariaDB root user password
  mysql_user: check_implicit_admin=False name=root host="{{ item }}" password="{{ mariadb_root_password }}"
  when: not (mariadb_root_password is undefined or mariadb_root_password|trim == "")
  ignore_errors: yes
  with_items:
    - "::1"
    - "{{ inventory_hostname }}"
    - "{{ inventory_hostname_short }}"
    - "localhost"
    - "127.0.0.1"

- name: Copy .my.cnf file to root home
  template: src=root.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600 force=yes
  when: not (mariadb_root_password is undefined or mariadb_root_password|trim == "")

- name: Update MariaDB root user password when root/nopassword allowed
  mysql_user: check_implicit_admin=True name=root password="{{ mariadb_root_password }}"

# Remove local
- mysql_user: login_user=root login_password="{{ mariadb_root_password }}" host={{ item }} name='' state=absent
  with_items:
    - "::1"
    - "{{ inventory_hostname }}"
    - "{{ inventory_hostname_short }}"
    - "localhost"
    - "127.0.0.1"

# PHPMyAdmin
- include: phpmyadmin.yml
  when: mariadb_phpmyadmin_install == true

# Percona tools
- include: percona.yml
  when: mariadb_percona_install == true

# Start
- service: name=mysql state=started enabled=yes
