---

# Install the Percona Toolkit
# https://www.percona.com/doc/percona-toolkit/2.2/index.html
# https://www.percona.com/downloads/percona-toolkit/

- get_url: url=https://www.percona.com/downloads/percona-toolkit/2.2.16/tarball/percona-toolkit-2.2.16.tar.gz mode=0644
  args:
    dest: /tmp/percona-toolkit.tar.gz

- unarchive: src=/tmp/percona-toolkit.tar.gz dest=/tmp
  args:
    copy: no
    group: "{{ mariadb_group }}"
    owner: "{{ mariadb_user }}"

- apt: name={{ item }} state=present
  with_items:
    - perl

# tar --exclude="*/*" -tf /tmp/percona-toolkit.tar.gz ﻿| sed -e "s/\///g" | head -1

- shell: perl Makefile.PL chdir={{ mariadb_percona_build_path }}
- shell: make chdir={{ mariadb_percona_build_path }}
- shell: make test chdir={{ mariadb_percona_build_path }}
- shell: make install chdir={{ mariadb_percona_build_path }}

# Example command:
# ﻿sudo /usr/local/bin/pt-summary