---

- name: Create sha256 checksum file
  shell: "echo \"{{ mariadb_phpmyadmin_sha256 }}  phpMyAdmin-{{ mariadb_phpmyadmin_version }}-all-languages.tar.gz\" > phpMyAdmin-{{ mariadb_phpmyadmin_version }}-all-languages.tar.gz.sha256"
  args:
    chdir: /tmp

- name: Download phpmyadmin
  get_url: url=https://files.phpmyadmin.net/phpMyAdmin/{{ mariadb_phpmyadmin_version }}/phpMyAdmin-{{ mariadb_phpmyadmin_version }}-all-languages.tar.gz mode=0644
  args:
    dest: /tmp/phpMyAdmin-{{ mariadb_phpmyadmin_version }}-all-languages.tar.gz

- name: Checksum sha256
  shell: sha256sum phpMyAdmin-{{ mariadb_phpmyadmin_version }}-all-languages.tar.gz.sha256 -c
  args:
    chdir: /tmp

- name: Unarchive phpmyadmin
  unarchive:
    src: "/tmp/phpMyAdmin-{{ mariadb_phpmyadmin_version }}-all-languages.tar.gz"
  args:
    copy: no
    group: "{{ mariadb_group }}"
    owner: "{{ mariadb_user }}"
    dest: "{{ mariadb_phpmyadmin_build_path }}"

- name: Remove old phpmyadmin
  shell: rm /usr/share/phpmyadmin -R
  ignore_errors: yes

- name: Move phpmyadmin to /usr/share/phpmyadmin
  shell: mv /tmp/phpMyAdmin-4.7.2-all-languages /usr/share/phpmyadmin

- name: Create phpmyadmin user
  mysql_user: name=phpmyadmin password="{{ mariadb_phpmyadmin_pw }}"
  when: (not (mariadb_phpmyadmin_pw is undefined or mariadb_phpmyadmin_pw|trim == "")) and (mariadb_disable_user_management == false)

- name: Create PMA user
  mysql_user: name=pma password="{{ mariadb_phpmyadmin_pw_controluser }}" priv=mysql.*:SELECT/phpmyadmin.*:ALL
  when: not (mariadb_phpmyadmin_pw_controluser is undefined or mariadb_phpmyadmin_pw_controluser|trim == "") and (mariadb_disable_user_management == false)

- name: Create nginx phpmyadmin.conf
  template: src=phpmyadmin.nginx.conf.j2 dest=/etc/nginx/sites-available/phpmyadmin.conf

- name: Create config.inc.php
  template: src="phpmyadmin.config.php.j2" dest="/usr/share/phpmyadmin/config.inc.php"

# An X.509 certificate (currently X.509v3) acts as a container for the public key that may be used to verify or
# validate an end entity (EE) such as a web site or an LDAP server. The entity is defined in the subject field
# of the certificate. The subject is described in the form of a Distinguished Name (DN) - backgrounder about
# DNs in LDAP - which is comprised of a number of Relative Distinguished Names (RDNs) each of which is a
# data-containing element called an Attribute. Specifically, the CN (commonName) attribute (RDN) of the Distinguished
# Name typically contains the end-entity covered by the certificate. An example of a CN may be a web site address
# such as CN=www.example.com. A full subject DN may contain one or more of the following RDNs CN= (commonName, the
# end-entity being covered, example, a website or www.example.com), C= (country), ST= (state or province within
# country), L= (location , nominally an address but ambiguously used except in EV certificates where it is rigorously
# defined), OU= (organizationalUnitName, a company division name or similar sub-structure), O= (organizationName,
# typically a company name).

- name: Create etc directory
  file: path="/etc/phpmyadmin" recurse=yes state=directory mode="u=rw,g=r,o=r"

- name: Create SSL keys for phpmyadmin
  shell: "openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/phpmyadmin/cert.key -out /etc/phpmyadmin/cert.crt -subj \"/C=NL/ST=ZH/L=Rotterdam/O=IT/CN={{ inventory_hostname }}\""
  args:
    creates: /etc/phpmyadmin/cert.key

- name: Enable nginx phpmyadmin site
  file: src=/etc/nginx/sites-available/phpmyadmin.conf dest=/etc/nginx/sites-enabled/phpmyadmin.conf
  args:
    owner: root
    group: root
    state: link

- name: Restart nginx
  service: name=nginx state=restarted
